apiVersion: v1
data:
  .git-credentials: aHR0cHM6Ly9lZGdlLXVzZXItMTpvcGVuZGF0YWh1YkBodHRwOi8vZ2l0ZWEtYWktZWRnZS1yaG9haS1lZGdlLWFjbS5hcHBzLnJob2FpLWVkZ2UtYWNtLXBvYy5yaGFpc2VuZy5jb20K
  .gitconfig: W2NyZWRlbnRpYWwgImh0dHA6Ly9naXRlYS1haS1lZGdlLXJob2FpLWVkZ2UtYWNtLmFwcHMucmhvYWktZWRnZS1hY20tcG9jLnJoYWlzZW5nLmNvbSJdCiAgaGVscGVyID0gc3RvcmUK
kind: Secret
metadata:
  creationTimestamp: "2023-08-31T14:50:11Z"
  name: gitea-edge-user-1-basic-auth
  namespace: gryan-pipelines
  resourceVersion: "39481930"
  uid: 24caf814-073d-4420-8374-62383d6db9af
type: Opaque
