apiVersion: v1
data:
  token: YjE0ZTlmNWRlOWZhYmI0OGEwOTFhNTZhMjQxNDAwMjVmYTU0MTZiYQ==
kind: Secret
metadata:
  creationTimestamp: "2023-08-31T14:30:08Z"
  name: gitea
  namespace: gryan-pipelines
  resourceVersion: "39452475"
  uid: b4ce3cba-ce64-4bfd-8218-1974b266cf2a
type: Opaque
