apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - servicemonitor-matchlabels.yaml
labels:
  - includeSelectors: true
    pairs:
      app: bike-rental-app
resources:
  - ../../base
  - bike-servicemonitor.yaml
  - bike-rental-inference-generator-cronjob.yaml
namespace: bike-rental-app
namePrefix: bike-rental-app-
commonLabels:
  app: bike-rental-app-1
configMapGenerator:
  - name: test-data
    files:
      - files/test-data.json
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: model-1
      spec:
        template:
          spec:
            containers:
              - name: model
                readinessProbe:
                  httpGet:
                    path: /v2/models/bike-rentals-auto-ml/ready
    target:
      kind: Deployment
replacements:
  - source:
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          group: route.openshift.io
          kind: Route
        fieldPaths:
          - spec.to.name
  - source:
      kind: Service
      fieldPath: metadata.labels.app
    targets:
      - select:
          group: monitoring.coreos.com
          kind: ServiceMonitor
        fieldPaths:
          - spec.selector.matchLabels.app
  - source:
      kind: ConfigMap
      name: test-data
      fieldPath: metadata.name
    targets:
      - select:
          kind: CronJob
          name: bike-rental-inference-generator
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.volumes.*.configMap.name
images:
  - name: edge-model-template-image
    newName: quay.io/grdryn/bike-rentals-auto-ml
    digest: sha256:2d66c6aff3e703f69c37d27f847365fb5fada875daae46c78b1439e25ba9d87e
