apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - multiclusterobservability.yaml

namespace: open-cluster-management-observability

configMapGenerator:
  - name: grafana-dashboard-edge-inference-health
    files:
    - grafana-dashboards/edge-inference-health.json
    options:
      annotations:
        observability.open-cluster-management.io/dashboard-folder: "Edge"
      labels:
        grafana-custom-dashboard: "true"
  - name: observability-metrics-custom-allowlist
    files:
    - files/uwl_metrics_list.yaml
    options:
      disableNameSuffixHash: true

secretGenerator:
- name: thanos-object-storage
  files:
  - secrets/thanos.yaml
  options:
    disableNameSuffixHash: true   
